### ISSUE TITLE
Add exploding hits

### ISSUE THREAD

**Issue by akabbeke** [akabbeke/WarhammerStatsEngine#2]
Some abilities allow for extra or "exploding" hits on either an unmodified or N+ roll. I think that this can be implemented by generating a secondary hit dist when we do the normal hit dist and convolving them.

**Comment by kiciek** [comment]
Example of problematic exploding hits is Necron immortal unit with teslas with MWBD(+1 to hit affecting teslas) and stratagem giving exploding hit on unmodified 6+.
IMO instead of selecting single hit modifier user should select any number of modifiers and select if they work on unmodified dice or modified.
